### ISSUE TITLE
typeerror pip install version

### ISSUE THREAD

**Issue by changhoonhahn** [Ciela-Institute/tarp#1]
I ran into this issue with the `pip install tarp` version of the package

```
~/.conda/envs/sbi/lib/python3.7/site-packages/tarp/drp.py in <module>
     10     theta: np.ndarray,
     11     references: str | np.ndarray = "random",
---> 12     metric: str = "euclidean",
     13 ) -> Tuple[np.ndarray, np.ndarray]:
     14     """
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

Installing the github version works without a problem

**Comment by adam-coogan** [comment]
Hi @changhoonhahn, I've created a new release and updated the version on PyPI to fix this.

In case you're wondering: the error you're seeing is a compatibility issue between older python versions (you're using 3.7) and the type annotations we were originally using. As of python 3.10, `Union[A, B]` is equivalent to `A | B` (see [pep 0604](https://peps.python.org/pep-0604/)). However, we changed back to the `Union` syntax since readthedocs uses python 3.9. In the process we forgot to reupload to PyPI. 

Thanks for flagging this!
